### ISSUE TITLE
get stuck in language selection

### ISSUE THREAD

**Issue by sysnasri** [dustinrue/proxmox-packer#7]
Hi,

I can't build artifact from this repo! the vm stuck in language selection and doesn't proceed.

**Comment by dustinrue** [comment]
for which OS?

**Comment by AnthonyTippy** [comment]
![image](https://github.com/dustinrue/proxmox-packer/assets/40606082/42500178-730f-4f3d-b9d2-db08e703a332)
Im having the same issue for ubuntu 22.04.  Any idea why it gets stuck here?  I've tried different versions and have the same issue.

Heres my packer logs. 
```
packer build -var-file variables.pkrvars.hcl ubuntu2204/packer.pkr.hcl
Warning: proxmox is deprecated, please use proxmox-iso instead

  on ubuntu2204/packer.pkr.hcl line 70:
  (source code not available)


proxmox.autogenerated_1: output will be in this color.

==> proxmox.autogenerated_1: Creating VM
==> proxmox.autogenerated_1: No VM ID given, getting next free from Proxmox
==> proxmox.autogenerated_1: Starting VM
==> proxmox.autogenerated_1: Starting HTTP server on port 8706
==> proxmox.autogenerated_1: Waiting 10s for boot
==> proxmox.autogenerated_1: Typing the boot command
==> proxmox.autogenerated_1: Waiting for SSH to become available...

[ after about 20 minutes]

==> proxmox.autogenerated_1: Timeout waiting for SSH.
==> proxmox.autogenerated_1: Stopping VM
==> proxmox.autogenerated_1: Deleting VM
Build 'proxmox.autogenerated_1' errored after 30 minutes 31 seconds: Timeout waiting for SSH.

==> Wait completed after 30 minutes 31 seconds

==> Some builds didn't complete successfully and had errors:
--> proxmox.autogenerated_1: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.
```

**Comment by rarrais** [comment]
Facing the exact same issue for Ubuntu 22.04.

**Comment by crasite** [comment]
I had this issue too, but it turned out to be a misconfiguration from my side.
The user-data file must start with
```
#cloud-config
```
and not 
```
##cloud-config
```

I think the reason that it goes back to normal installation screen is either because
1. misconfiguration on the user-data file or
2. Proxmox is not able to connect to the CloudInit server (your pc running the command)

for the second reasons, you could try setting your ip directly
```

source "proxmox" "autogenerated_1" {
   ......
    http_bind_address = "192.168.1.104"
    http_port_min = 8802
    http_port_max = 8802
}

**Comment by dustinrue** [comment]
What @crasite says here is likely the cause, the cloud config file is not properly being recognized
